### ISSUE TITLE
Ejemplo toma de datos web por REST-API

### ISSUE THREAD

**Issue by franktoffel** [CAChemE/curso-python-datos#2]
https://github.com/swcarpentry/web-data-python#web-data-python

**Comment by franktoffel** [comment]
Ejemplo mínimo: https://github.com/CAChemE/curso-python-datos/blob/api-rest-aemet/notebooks/500-AEMET_APIREST.ipynb

Añadir comentarios y quizás refactorizar código utilizando una clase.
En el material de swcarpentry viene explicado de forma bastante clara como pelearse con archivos csv e importarlos.

**Comment by AlexS12** [comment]
Añadida la introducción y mejorado el ejemplo.

Falta:

- [x]  conclusiones
- [x] resumen
- [x] links

mejorar la función que resume la adquisición de datos
