### ISSUE TITLE
Scipy Lectures (resumen)

### ISSUE THREAD

**Issue by franktoffel** [CAChemE/curso-python-datos#4]
Repaso a las funciones principales de SciPy en base a las SciPyLectures y Aeropython

**Comment by franktoffel** [comment]
- [x] Contenido básico 
- [ ] ejercicios con importando datos reales (quizás podemos dejarlos para pandas)

**Comment by AlexS12** [comment]
Yo veo bien la parte que has puesto. Si quieres la carga y guardado de datos sencillos (lo que es sólo números) la contamos al pasar por numpy. El resto, cabeceras, datos mezclados, missing... lo vemos con pandas

**Comment by franktoffel** [comment]
Sí, numpy leerla los datos de software-carpentry que están preparados para no dar problemas.

Cerramos Issue.
