### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by franktoffel** [CAChemE/curso-python-datos#5]
Trabajo con pandas para análisis de datos y representación de gráficas (en base al material de AeroPython).
Añadir ejemplo final de AEMET

**Comment by AlexS12** [comment]
Añadido el notebook inicial. Estoy bajando unos datos de AEMET y si me cuadran los cambio por los que hay

**Comment by AlexS12** [comment]
Al final he hecho un ejemplo más con datos de AEMET, es muy denso, solo lo voy a comentar por encima y se lo dejo de regalo para que lo tengan de ejemplo de otras cosas que puedan hacer. La API de AEMET es un poco floja sinceramente.

Cerrado esto!

**Comment by franktoffel** [comment]
¿Añadimos la intro de AeroPython a Pandas entonces, no?

**Comment by AlexS12** [comment]
Sí porque tenemos más datos que de AEMET. Los datos de AEMET empiezan hace muy poco tiempo. Están cargados en el segundo notebook de requests.
